//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyProfile
    {
        public int Id { get; set; }
        public string StockCode { get; set; }
        public string LegalName { get; set; }
        public string EnglishName { get; set; }
        public Nullable<System.DateTime> EstablishDate { get; set; }
        public string OwnedIndustry { get; set; }
        public Nullable<decimal> RegisteredCapital { get; set; }
        public Nullable<decimal> IssuePrice { get; set; }
        public Nullable<int> EmployeesCount { get; set; }
        public string LegalPerson { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string OfficeAddress { get; set; }
        public Nullable<System.DateTime> ListingDate { get; set; }
        public string BusinessScope { get; set; }
        public string Profile { get; set; }
        public string ListedMarket { get; set; }
    }
}
