//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThirdPartyAccount
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string OpenId { get; set; }
        public Nullable<int> AccountType { get; set; }
        public Nullable<System.DateTime> AuthDate { get; set; }
        public bool Deleted { get; set; }
    }
}
